### ISSUE TITLE
Mockclient calls to Docker mockserver *really* slow 

### ISSUE THREAD

**Issue by mbjelac** [jamesdbloom/mockserver#380]
Calls to mockserver in my tests (i.e. reset and setting up expectations) each have an overhead of about 4.5 seconds.

Calls to the mockserver server instance (started in a Docker container) from my SUT are fast.

- using mockserver library: `3.10.4`
- server started in Docker with `docker-compose`:
```yaml
version: '3.3'

services:
  mockserver:
    image: jamesdbloom/mockserver:latest
    ports:
    - 1080:1080
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"
```

What am I doing wrong?
