### ISSUE TITLE
Cannot bind port 80 inside the mockserver container 

### ISSUE THREAD

**Issue by lindycoder** [jamesdbloom/mockserver#585]
Hello, since #566 has been merged, it breaks my container as they try to listen on port 80.

My use case is this kind of docker-compose:
```
services: 
services:
  myapp:
    image: ...
    networks:
      - my-network

  mock-server:
    image: jamesdbloom/mockserver:latest
    command: /opt/mockserver/run_mockserver.sh -serverPort 80

    networks:
      my-network:
        aliases:
          - dependency-one.mockserver
          - dependency-two.mockserver

networks:
  my-network:
```

The i configure my application with dependencies being "http://dependency-one.mockserver/" and "http://dependency-two.mockserver/"

And it works great because mockserver runs on port 80 and my application does not have to use  a weird port to access their dependencies and this is one of the great thing about using mock-server in a docker-network.

I Know i can change my docker-compose to use `user: root`  in order to bind ports < 1024  but i was wondering if there was another solution or someway to allow the current user to bind port 80.

Thanks!

**Comment by jamesdbloom** [comment]
As far as I am aware there is no option other then using `user: root`, for example the following works:

```yaml
version: "3"
services:
  mockserver-source:
    image: jamesdbloom/mockserver:mockserver-5.5.1
    command: /opt/mockserver/run_mockserver.sh -serverPort 80
    user: root
    ports:
      - 1081:80
    environment:
      - LOG_LEVEL=INFO
    networks:
      - mynetwork
  mockserver-target:
    image: jamesdbloom/mockserver:mockserver-5.5.1
    command: /opt/mockserver/run_mockserver.sh -serverPort 80
    user: root
    ports:
      - 1082:80
    environment:
      - LOG_LEVEL=INFO
    networks:
      mynetwork:
        aliases:
          - target.mockserver-target
networks:
  mynetwork:
```

```bash
#!/usr/bin/env bash

curl -k -X PUT https://localhost:1081/mockserver/reset
curl -k -X PUT https://localhost:1081/mockserver/expectation --data '{
    "httpRequest": {
        "path": "/source",
        "method": "GET"
    },
    "httpOverrideForwardedRequest": {
        "httpRequest": {
            "headers": {
                "Host": [ "target.mockserver-target:80" ]
            },
            "path": "/target"
        }
    },
    "times": {
        "unlimited": true
    }
}'

curl -k -X PUT https://localhost:1082/mockserver/reset
curl -k -X PUT https://localhost:1082/mockserver/expectation --data '{
    "httpRequest": {
        "method": "GET",
        "path": "/target"
    },
    "httpResponse": {
        "statusCode": 200,
        "headers": {
            "Content-Length": [ "20" ]
        },
        "body": "some target response"
    },
    "times": {
    "unlimited": true
    }
}'

curl -v -k https://localhost:1081/source && echo
```

Although it is possible to using port mapping for both `bridge` and `overlay` networks in docker neither or these change the port that is exposed inside the network.  In both cases the port mapping only exposes that port outside the network.

In addition the change that was made in #566 was to run the process inside the container under a non-root user.  So added the `user: root` just effectively reverses that change.

I am going to close this ticket, as I don't believe the solution is to use `user: root`
