### ISSUE TITLE
Unable to set serverPort to 80

### ISSUE THREAD

**Issue by codan84** [jamesdbloom/mockserver#641]
This server is a job well done and I would like to run it in docker-compose together with my rest API, with networking setup so that any requests my rest API does go to this mock server. Unfortunately I can't make the mock server to listen on port 80, and I don't want to make acceptance-tests specific changes in a production code of the rest API.  
Here is an example docker-compose file:
```
version: '2'

services:
  external-api-mock:
    container_name: external-api-mock
    image: jamesdbloom/mockserver
    environment:
      SERVER_PORT: 80
    networks:
      default:
        aliases:
          - external-api.co.uk
  my-api-prod:
    container_name: my-api-prod
    build:
      context: ../../
      dockerfile: docker/acceptance-tests/prod.Dockerfile
    volumes:
      - ${PWD}/package.json:/my-api/package.json
      - my-api-dist:/my-api/dist/
      - my-api-node-modules:/my-api/node_modules/
    ports:
      - "8081:8081"
    networks:
      default:
        aliases:
          - my-api.co.uk
    entrypoint: npm run start:prod
```

`my-api` when called will make calls in turn to `external-api.co.uk`, but will make these calls on port 80 (default). I would imagine this would be quite common scenario. Unfortunately mock server will fail to bind to port 80.

**Comment by jamesdbloom** [comment]
This is because the default user the mockserver container runs as is not root, so you get an error as follows:

```bash
$ docker-compose up
Creating docker_mockServer_1 ... done
Attaching to docker_mockServer_1
mockServer_1  | 
mockServer_1  | java  -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 80 -logLevel INFO &
mockServer_1  | 
mockServer_1  | Exception in thread "main" java.lang.RuntimeException: Exception while binding MockServer to port 80
mockServer_1  | 	at org.mockserver.lifecycle.LifeCycle.bindPorts(LifeCycle.java:165)
mockServer_1  | 	at org.mockserver.lifecycle.LifeCycle.bindServerPorts(LifeCycle.java:123)
mockServer_1  | 	at org.mockserver.mockserver.MockServer.createServerBootstrap(MockServer.java:104)
mockServer_1  | 	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:45)
mockServer_1  | 	at org.mockserver.mockserver.MockServer.<init>(MockServer.java:35)
mockServer_1  | 	at org.mockserver.cli.Main.main(Main.java:86)
mockServer_1  | Caused by: java.net.SocketException: Permission denied
mockServer_1  | 	at sun.nio.ch.Net.bind0(Native Method)
mockServer_1  | 	at sun.nio.ch.Net.bind(Net.java:433)
mockServer_1  | 	at sun.nio.ch.Net.bind(Net.java:425)
mockServer_1  | 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
mockServer_1  | 	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
mockServer_1  | 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:563)
mockServer_1  | 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332)
mockServer_1  | 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
mockServer_1  | 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
mockServer_1  | 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
mockServer_1  | 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:259)
mockServer_1  | 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366)
mockServer_1  | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
mockServer_1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:405)
mockServer_1  | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
mockServer_1  | 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906)
mockServer_1  | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
mockServer_1  | 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
mockServer_1  | 	at java.lang.Thread.run(Thread.java:748)
```
To resolve this you need to add a `user: root` configuration to you `docker-compose.yaml` file, as follows:

```yaml
 mockServer:
   image: jamesdbloom/mockserver:mockserver-5.5.4
   ports:
   - 1080:1080
   user: root
   environment:
   - LOG_LEVEL=INFO
   - SERVER_PORT=80
```

Once you do this the container runs as root so you can bind to port lower then 1024 as follows:

```bash
$ docker-compose up
Creating docker_mockServer_1 ... done
Attaching to docker_mockServer_1
mockServer_1  | 
mockServer_1  | java  -Dfile.encoding=UTF-8 -jar /opt/mockserver/mockserver-netty-jar-with-dependencies.jar  -serverPort 80 -logLevel INFO &
mockServer_1  | 
mockServer_1  | 2019-06-18 20:13:24,388 INFO o.m.m.HttpStateHandler started on port: 80
```
